stages:
  - build
  - deploy

services:
  - docker:dind

build:
  image: docker:19.03.8
  environment:
    name: backend/$CI_COMMIT_REF_NAME
  stage: build
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email)
  script:
    - docker build -t $REPOSITORY_URL:$CI_COMMIT_REF_NAME .
    - docker push $REPOSITORY_URL:$CI_COMMIT_REF_NAME
  only:
    - development

deploy development:
  environment:
    name: backend/$CI_COMMIT_REF_NAME
  stage: deploy
  before_script:
    - which ssh-agent || { apk add --no-cache openssh-client; }
    - eval $(ssh-agent -s)
    - cat $GINGER_DEVELOPMENT_CLUSTER_PRIVATE_KEY | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $GINGER_DEVELOPMENT_CLUSTER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $GINGER_DEVELOPMENT_CLUSTER_USER@$GINGER_DEVELOPMENT_CLUSTER_HOST '~/ginger/update-backend.sh'
  only:
    - development
