version: '3'
services:
  app:
    container_name: ginger-back
    restart: always
    build:
      context: .
    ports:
      - '6001:6001'
    links:
      - redis
  redis:
    image: 'redis:4.0'
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    ports:
      - '6379:6379'
